### ISSUE TITLE
dry_run is not passed though corrrectly

### ISSUE THREAD

**Issue by OJWatson** [mrc-ide/syncr#2]
translate the underscore to a hyphen

**Comment by jsta** [comment]
`dry_run` works fine for me.

**Comment by jsta** [comment]
@OJWatson maybe you did not see any output because you did not set `verbose = TRUE`?

**Comment by richfitz** [comment]
The error is [here](https://github.com/richfitz/syncr/blob/5e714f0/R/syncr.R#L61), fixed in ab6d032

Looks like on the linux version of rsync, `--dry_run` is interpreted as `--dry-run` but in Windows/Rtools the arguments are parsed more strictly.
