### ISSUE TITLE
Difficulty transferring the contents of directories

### ISSUE THREAD

**Issue by jsta** [mrc-ide/syncr#4]
I am having difficulty transferring the **contents** of a directory without transferring the directory itself.

``` r
syncr::rsync(paste0(file.path(system.file(), "html"), .Platform$file.sep),
 tempdir(), verbose = TRUE, archive = TRUE)
list.files(tempdir())
```

I expect the output to match `list.files(file.path(system.file(), "html"))`:

> [1] "00Index.html" "R.css"       

but instead I see:

> [1] "html"

**Comment by richfitz** [comment]
Can you try passing `drop_src_directory = TRUE` as an argument there?  This should toggle between the two behaviours

**Comment by jsta** [comment]
That works, thanks. I would have expected the trailing slash on the source directory to toggle the two behaviors rather than a function argument.

**Comment by richfitz** [comment]
> I would have expected the trailing slash to toggle the two behaviors rather than a function argument

Out of curiosity, why?  I presume because that's what `rsync` does (that behaviour and my inability to remember them) is one of the main reasons I wrote this package :grinning:

**Comment by jsta** [comment]
Yes, that is what `rsync` does.
